### ISSUE TITLE
Map visualization not scalable

### ISSUE THREAD

**Issue by bertolla** [ilvalle/w2panalytics#26]
The application is not loading data from multiple stations of Meteo. The data is beeing loaded EAGERLY on the front-end instead of LAZY. This means that the application is not able to display the data and goes  in timeout.
E.g. The data, like the temperature of a single station should be fetched when the  user clicks on the station icon.

Now we have more than 100 Meteostation and we can't visualize them.

**Comment by alessiovaralta** [comment]
I have changed the code and I have made the pull request. Now I put the marker on the map and there is a onclick event that retrieves the data for the single station. For the graphic there is a little problem because there are many data, one for row and so in base of the position of the station on the screen there is the possibility that a part of this is hidden and so required a scroll of mouse.

**Comment by bertolla** [comment]
Works fluently and looks great on the map of southytyrol. We have to rethink the popup design but its better and faster now . Good job!

**Comment by bertolla** [comment]
After checking again I noticed a problem. All stations show all type of data even thought not all have it available and give false information to the end-users. Before calling get-records it would be wiser to user get-data-types with station as parameter so you can filter the types each station supports and also do less calls to the api.

**Comment by alessiovaralta** [comment]
I have made a new pull request, now i filter the type in base of the id-station

**Comment by rcavaliere** [comment]
Patrick, have you already uploaded online this new version of the application?
